// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApkEntry.proto

package com.android.fastdeploy;

public final class ApkEntryProto {
  private ApkEntryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_fastdeploy_APKDump_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_fastdeploy_APKDump_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_fastdeploy_APKEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_fastdeploy_APKEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_fastdeploy_APKMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_fastdeploy_APKMetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ApkEntry.proto\022\026com.android.fastdeploy" +
      "\"M\n\007APKDump\022\014\n\004name\030\001 \001(\t\022\n\n\002cd\030\002 \001(\014\022\021\n" +
      "\tsignature\030\003 \001(\014\022\025\n\rabsolute_path\030\004 \001(\t\"" +
      "=\n\010APKEntry\022\013\n\003md5\030\001 \001(\014\022\022\n\ndataOffset\030\002" +
      " \001(\003\022\020\n\010dataSize\030\003 \001(\003\"W\n\013APKMetaData\022\025\n" +
      "\rabsolute_path\030\001 \001(\t\0221\n\007entries\030\002 \003(\0132 ." +
      "com.android.fastdeploy.APKEntryB)\n\026com.a" +
      "ndroid.fastdeployB\rApkEntryProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_android_fastdeploy_APKDump_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_android_fastdeploy_APKDump_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_fastdeploy_APKDump_descriptor,
        new java.lang.String[] { "Name", "Cd", "Signature", "AbsolutePath", });
    internal_static_com_android_fastdeploy_APKEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_android_fastdeploy_APKEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_fastdeploy_APKEntry_descriptor,
        new java.lang.String[] { "Md5", "DataOffset", "DataSize", });
    internal_static_com_android_fastdeploy_APKMetaData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_android_fastdeploy_APKMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_fastdeploy_APKMetaData_descriptor,
        new java.lang.String[] { "AbsolutePath", "Entries", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
