// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApkEntry.proto

package com.android.fastdeploy;

public interface APKEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.fastdeploy.APKEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes md5 = 1;</code>
   * @return The md5.
   */
  com.google.protobuf.ByteString getMd5();

  /**
   * <code>int64 dataOffset = 2;</code>
   * @return The dataOffset.
   */
  long getDataOffset();

  /**
   * <code>int64 dataSize = 3;</code>
   * @return The dataSize.
   */
  long getDataSize();
}
