// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApkEntry.proto

package com.android.fastdeploy;

public interface APKMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.fastdeploy.APKMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string absolute_path = 1;</code>
   * @return The absolutePath.
   */
  java.lang.String getAbsolutePath();
  /**
   * <code>string absolute_path = 1;</code>
   * @return The bytes for absolutePath.
   */
  com.google.protobuf.ByteString
      getAbsolutePathBytes();

  /**
   * <code>repeated .com.android.fastdeploy.APKEntry entries = 2;</code>
   */
  java.util.List<com.android.fastdeploy.APKEntry> 
      getEntriesList();
  /**
   * <code>repeated .com.android.fastdeploy.APKEntry entries = 2;</code>
   */
  com.android.fastdeploy.APKEntry getEntries(int index);
  /**
   * <code>repeated .com.android.fastdeploy.APKEntry entries = 2;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .com.android.fastdeploy.APKEntry entries = 2;</code>
   */
  java.util.List<? extends com.android.fastdeploy.APKEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .com.android.fastdeploy.APKEntry entries = 2;</code>
   */
  com.android.fastdeploy.APKEntryOrBuilder getEntriesOrBuilder(
      int index);
}
