// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adb_known_hosts.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_adb_5fknown_5fhosts_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_adb_5fknown_5fhosts_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_adb_5fknown_5fhosts_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_adb_5fknown_5fhosts_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_adb_5fknown_5fhosts_2eproto;
namespace adb {
namespace proto {
class AdbKnownHosts;
struct AdbKnownHostsDefaultTypeInternal;
extern AdbKnownHostsDefaultTypeInternal _AdbKnownHosts_default_instance_;
class HostInfo;
struct HostInfoDefaultTypeInternal;
extern HostInfoDefaultTypeInternal _HostInfo_default_instance_;
}  // namespace proto
}  // namespace adb
PROTOBUF_NAMESPACE_OPEN
template<> ::adb::proto::AdbKnownHosts* Arena::CreateMaybeMessage<::adb::proto::AdbKnownHosts>(Arena*);
template<> ::adb::proto::HostInfo* Arena::CreateMaybeMessage<::adb::proto::HostInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace adb {
namespace proto {

// ===================================================================

class HostInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:adb.proto.HostInfo) */ {
 public:
  inline HostInfo() : HostInfo(nullptr) {}
  ~HostInfo() override;
  explicit PROTOBUF_CONSTEXPR HostInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HostInfo(const HostInfo& from);
  HostInfo(HostInfo&& from) noexcept
    : HostInfo() {
    *this = ::std::move(from);
  }

  inline HostInfo& operator=(const HostInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline HostInfo& operator=(HostInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HostInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const HostInfo* internal_default_instance() {
    return reinterpret_cast<const HostInfo*>(
               &_HostInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HostInfo& a, HostInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(HostInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HostInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HostInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HostInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HostInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HostInfo& from) {
    HostInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HostInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "adb.proto.HostInfo";
  }
  protected:
  explicit HostInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGuidFieldNumber = 1,
  };
  // string guid = 1;
  void clear_guid();
  const std::string& guid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guid();
  PROTOBUF_NODISCARD std::string* release_guid();
  void set_allocated_guid(std::string* guid);
  private:
  const std::string& _internal_guid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guid(const std::string& value);
  std::string* _internal_mutable_guid();
  public:

  // @@protoc_insertion_point(class_scope:adb.proto.HostInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adb_5fknown_5fhosts_2eproto;
};
// -------------------------------------------------------------------

class AdbKnownHosts final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:adb.proto.AdbKnownHosts) */ {
 public:
  inline AdbKnownHosts() : AdbKnownHosts(nullptr) {}
  ~AdbKnownHosts() override;
  explicit PROTOBUF_CONSTEXPR AdbKnownHosts(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AdbKnownHosts(const AdbKnownHosts& from);
  AdbKnownHosts(AdbKnownHosts&& from) noexcept
    : AdbKnownHosts() {
    *this = ::std::move(from);
  }

  inline AdbKnownHosts& operator=(const AdbKnownHosts& from) {
    CopyFrom(from);
    return *this;
  }
  inline AdbKnownHosts& operator=(AdbKnownHosts&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AdbKnownHosts& default_instance() {
    return *internal_default_instance();
  }
  static inline const AdbKnownHosts* internal_default_instance() {
    return reinterpret_cast<const AdbKnownHosts*>(
               &_AdbKnownHosts_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AdbKnownHosts& a, AdbKnownHosts& b) {
    a.Swap(&b);
  }
  inline void Swap(AdbKnownHosts* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AdbKnownHosts* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AdbKnownHosts* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AdbKnownHosts>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AdbKnownHosts& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AdbKnownHosts& from) {
    AdbKnownHosts::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdbKnownHosts* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "adb.proto.AdbKnownHosts";
  }
  protected:
  explicit AdbKnownHosts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostInfosFieldNumber = 1,
  };
  // repeated .adb.proto.HostInfo host_infos = 1;
  int host_infos_size() const;
  private:
  int _internal_host_infos_size() const;
  public:
  void clear_host_infos();
  ::adb::proto::HostInfo* mutable_host_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::adb::proto::HostInfo >*
      mutable_host_infos();
  private:
  const ::adb::proto::HostInfo& _internal_host_infos(int index) const;
  ::adb::proto::HostInfo* _internal_add_host_infos();
  public:
  const ::adb::proto::HostInfo& host_infos(int index) const;
  ::adb::proto::HostInfo* add_host_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::adb::proto::HostInfo >&
      host_infos() const;

  // @@protoc_insertion_point(class_scope:adb.proto.AdbKnownHosts)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::adb::proto::HostInfo > host_infos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adb_5fknown_5fhosts_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HostInfo

// string guid = 1;
inline void HostInfo::clear_guid() {
  _impl_.guid_.ClearToEmpty();
}
inline const std::string& HostInfo::guid() const {
  // @@protoc_insertion_point(field_get:adb.proto.HostInfo.guid)
  return _internal_guid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HostInfo::set_guid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.guid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:adb.proto.HostInfo.guid)
}
inline std::string* HostInfo::mutable_guid() {
  std::string* _s = _internal_mutable_guid();
  // @@protoc_insertion_point(field_mutable:adb.proto.HostInfo.guid)
  return _s;
}
inline const std::string& HostInfo::_internal_guid() const {
  return _impl_.guid_.Get();
}
inline void HostInfo::_internal_set_guid(const std::string& value) {
  
  _impl_.guid_.Set(value, GetArenaForAllocation());
}
inline std::string* HostInfo::_internal_mutable_guid() {
  
  return _impl_.guid_.Mutable(GetArenaForAllocation());
}
inline std::string* HostInfo::release_guid() {
  // @@protoc_insertion_point(field_release:adb.proto.HostInfo.guid)
  return _impl_.guid_.Release();
}
inline void HostInfo::set_allocated_guid(std::string* guid) {
  if (guid != nullptr) {
    
  } else {
    
  }
  _impl_.guid_.SetAllocated(guid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.guid_.IsDefault()) {
    _impl_.guid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:adb.proto.HostInfo.guid)
}

// -------------------------------------------------------------------

// AdbKnownHosts

// repeated .adb.proto.HostInfo host_infos = 1;
inline int AdbKnownHosts::_internal_host_infos_size() const {
  return _impl_.host_infos_.size();
}
inline int AdbKnownHosts::host_infos_size() const {
  return _internal_host_infos_size();
}
inline void AdbKnownHosts::clear_host_infos() {
  _impl_.host_infos_.Clear();
}
inline ::adb::proto::HostInfo* AdbKnownHosts::mutable_host_infos(int index) {
  // @@protoc_insertion_point(field_mutable:adb.proto.AdbKnownHosts.host_infos)
  return _impl_.host_infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::adb::proto::HostInfo >*
AdbKnownHosts::mutable_host_infos() {
  // @@protoc_insertion_point(field_mutable_list:adb.proto.AdbKnownHosts.host_infos)
  return &_impl_.host_infos_;
}
inline const ::adb::proto::HostInfo& AdbKnownHosts::_internal_host_infos(int index) const {
  return _impl_.host_infos_.Get(index);
}
inline const ::adb::proto::HostInfo& AdbKnownHosts::host_infos(int index) const {
  // @@protoc_insertion_point(field_get:adb.proto.AdbKnownHosts.host_infos)
  return _internal_host_infos(index);
}
inline ::adb::proto::HostInfo* AdbKnownHosts::_internal_add_host_infos() {
  return _impl_.host_infos_.Add();
}
inline ::adb::proto::HostInfo* AdbKnownHosts::add_host_infos() {
  ::adb::proto::HostInfo* _add = _internal_add_host_infos();
  // @@protoc_insertion_point(field_add:adb.proto.AdbKnownHosts.host_infos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::adb::proto::HostInfo >&
AdbKnownHosts::host_infos() const {
  // @@protoc_insertion_point(field_list:adb.proto.AdbKnownHosts.host_infos)
  return _impl_.host_infos_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace adb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_adb_5fknown_5fhosts_2eproto
