// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adb_known_hosts.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_adb_5fknown_5fhosts_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_adb_5fknown_5fhosts_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_adb_5fknown_5fhosts_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_adb_5fknown_5fhosts_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_adb_5fknown_5fhosts_2eproto;
namespace adb {
namespace proto {
class AdbKnownHosts;
struct AdbKnownHostsDefaultTypeInternal;
extern AdbKnownHostsDefaultTypeInternal _AdbKnownHosts_default_instance_;
class HostInfo;
struct HostInfoDefaultTypeInternal;
extern HostInfoDefaultTypeInternal _HostInfo_default_instance_;
}  // namespace proto
}  // namespace adb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace adb {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class HostInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:adb.proto.HostInfo) */ {
 public:
  inline HostInfo() : HostInfo(nullptr) {}
  ~HostInfo() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HostInfo(::google::protobuf::internal::ConstantInitialized);

  inline HostInfo(const HostInfo& from)
      : HostInfo(nullptr, from) {}
  HostInfo(HostInfo&& from) noexcept
    : HostInfo() {
    *this = ::std::move(from);
  }

  inline HostInfo& operator=(const HostInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline HostInfo& operator=(HostInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HostInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const HostInfo* internal_default_instance() {
    return reinterpret_cast<const HostInfo*>(
               &_HostInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HostInfo& a, HostInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(HostInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HostInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HostInfo* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HostInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HostInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HostInfo& from) {
    HostInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HostInfo* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "adb.proto.HostInfo";
  }
  protected:
  explicit HostInfo(::google::protobuf::Arena* arena);
  HostInfo(::google::protobuf::Arena* arena, const HostInfo& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGuidFieldNumber = 1,
  };
  // string guid = 1;
  void clear_guid() ;
  const std::string& guid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_guid(Arg_&& arg, Args_... args);
  std::string* mutable_guid();
  PROTOBUF_NODISCARD std::string* release_guid();
  void set_allocated_guid(std::string* value);

  private:
  const std::string& _internal_guid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guid(
      const std::string& value);
  std::string* _internal_mutable_guid();

  public:
  // @@protoc_insertion_point(class_scope:adb.proto.HostInfo)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      31, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr guid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adb_5fknown_5fhosts_2eproto;
};// -------------------------------------------------------------------

class AdbKnownHosts final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:adb.proto.AdbKnownHosts) */ {
 public:
  inline AdbKnownHosts() : AdbKnownHosts(nullptr) {}
  ~AdbKnownHosts() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AdbKnownHosts(::google::protobuf::internal::ConstantInitialized);

  inline AdbKnownHosts(const AdbKnownHosts& from)
      : AdbKnownHosts(nullptr, from) {}
  AdbKnownHosts(AdbKnownHosts&& from) noexcept
    : AdbKnownHosts() {
    *this = ::std::move(from);
  }

  inline AdbKnownHosts& operator=(const AdbKnownHosts& from) {
    CopyFrom(from);
    return *this;
  }
  inline AdbKnownHosts& operator=(AdbKnownHosts&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AdbKnownHosts& default_instance() {
    return *internal_default_instance();
  }
  static inline const AdbKnownHosts* internal_default_instance() {
    return reinterpret_cast<const AdbKnownHosts*>(
               &_AdbKnownHosts_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AdbKnownHosts& a, AdbKnownHosts& b) {
    a.Swap(&b);
  }
  inline void Swap(AdbKnownHosts* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AdbKnownHosts* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AdbKnownHosts* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AdbKnownHosts>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AdbKnownHosts& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AdbKnownHosts& from) {
    AdbKnownHosts::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AdbKnownHosts* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "adb.proto.AdbKnownHosts";
  }
  protected:
  explicit AdbKnownHosts(::google::protobuf::Arena* arena);
  AdbKnownHosts(::google::protobuf::Arena* arena, const AdbKnownHosts& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostInfosFieldNumber = 1,
  };
  // repeated .adb.proto.HostInfo host_infos = 1;
  int host_infos_size() const;
  private:
  int _internal_host_infos_size() const;

  public:
  void clear_host_infos() ;
  ::adb::proto::HostInfo* mutable_host_infos(int index);
  ::google::protobuf::RepeatedPtrField< ::adb::proto::HostInfo >*
      mutable_host_infos();
  private:
  const ::google::protobuf::RepeatedPtrField<::adb::proto::HostInfo>& _internal_host_infos() const;
  ::google::protobuf::RepeatedPtrField<::adb::proto::HostInfo>* _internal_mutable_host_infos();
  public:
  const ::adb::proto::HostInfo& host_infos(int index) const;
  ::adb::proto::HostInfo* add_host_infos();
  const ::google::protobuf::RepeatedPtrField< ::adb::proto::HostInfo >&
      host_infos() const;
  // @@protoc_insertion_point(class_scope:adb.proto.AdbKnownHosts)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::adb::proto::HostInfo > host_infos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adb_5fknown_5fhosts_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HostInfo

// string guid = 1;
inline void HostInfo::clear_guid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.guid_.ClearToEmpty();
}
inline const std::string& HostInfo::guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:adb.proto.HostInfo.guid)
  return _internal_guid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HostInfo::set_guid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.guid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:adb.proto.HostInfo.guid)
}
inline std::string* HostInfo::mutable_guid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_guid();
  // @@protoc_insertion_point(field_mutable:adb.proto.HostInfo.guid)
  return _s;
}
inline const std::string& HostInfo::_internal_guid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.guid_.Get();
}
inline void HostInfo::_internal_set_guid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.guid_.Set(value, GetArena());
}
inline std::string* HostInfo::_internal_mutable_guid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.guid_.Mutable( GetArena());
}
inline std::string* HostInfo::release_guid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:adb.proto.HostInfo.guid)
  return _impl_.guid_.Release();
}
inline void HostInfo::set_allocated_guid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.guid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.guid_.IsDefault()) {
          _impl_.guid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:adb.proto.HostInfo.guid)
}

// -------------------------------------------------------------------

// AdbKnownHosts

// repeated .adb.proto.HostInfo host_infos = 1;
inline int AdbKnownHosts::_internal_host_infos_size() const {
  return _internal_host_infos().size();
}
inline int AdbKnownHosts::host_infos_size() const {
  return _internal_host_infos_size();
}
inline void AdbKnownHosts::clear_host_infos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.host_infos_.Clear();
}
inline ::adb::proto::HostInfo* AdbKnownHosts::mutable_host_infos(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:adb.proto.AdbKnownHosts.host_infos)
  return _internal_mutable_host_infos()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::adb::proto::HostInfo>* AdbKnownHosts::mutable_host_infos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:adb.proto.AdbKnownHosts.host_infos)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_host_infos();
}
inline const ::adb::proto::HostInfo& AdbKnownHosts::host_infos(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:adb.proto.AdbKnownHosts.host_infos)
  return _internal_host_infos().Get(index);
}
inline ::adb::proto::HostInfo* AdbKnownHosts::add_host_infos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::adb::proto::HostInfo* _add = _internal_mutable_host_infos()->Add();
  // @@protoc_insertion_point(field_add:adb.proto.AdbKnownHosts.host_infos)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::adb::proto::HostInfo>& AdbKnownHosts::host_infos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:adb.proto.AdbKnownHosts.host_infos)
  return _internal_host_infos();
}
inline const ::google::protobuf::RepeatedPtrField<::adb::proto::HostInfo>&
AdbKnownHosts::_internal_host_infos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.host_infos_;
}
inline ::google::protobuf::RepeatedPtrField<::adb::proto::HostInfo>*
AdbKnownHosts::_internal_mutable_host_infos() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.host_infos_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace adb


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_adb_5fknown_5fhosts_2eproto_2epb_2eh
