// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApkEntry.proto

#include "ApkEntry.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace com {
namespace android {
namespace fastdeploy {

inline constexpr APKEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dataoffset_{::int64_t{0}},
        datasize_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR APKEntry::APKEntry(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct APKEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR APKEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~APKEntryDefaultTypeInternal() {}
  union {
    APKEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 APKEntryDefaultTypeInternal _APKEntry_default_instance_;

inline constexpr APKDump::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cd_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        signature_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        absolute_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR APKDump::APKDump(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct APKDumpDefaultTypeInternal {
  PROTOBUF_CONSTEXPR APKDumpDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~APKDumpDefaultTypeInternal() {}
  union {
    APKDump _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 APKDumpDefaultTypeInternal _APKDump_default_instance_;

inline constexpr APKMetaData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : entries_{},
        absolute_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR APKMetaData::APKMetaData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct APKMetaDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR APKMetaDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~APKMetaDataDefaultTypeInternal() {}
  union {
    APKMetaData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 APKMetaDataDefaultTypeInternal _APKMetaData_default_instance_;
}  // namespace fastdeploy
}  // namespace android
}  // namespace com
static ::_pb::Metadata file_level_metadata_ApkEntry_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ApkEntry_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ApkEntry_2eproto = nullptr;
const ::uint32_t TableStruct_ApkEntry_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKDump, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKDump, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKDump, _impl_.cd_),
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKDump, _impl_.signature_),
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKDump, _impl_.absolute_path_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKEntry, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKEntry, _impl_.md5_),
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKEntry, _impl_.dataoffset_),
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKEntry, _impl_.datasize_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKMetaData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKMetaData, _impl_.absolute_path_),
    PROTOBUF_FIELD_OFFSET(::com::android::fastdeploy::APKMetaData, _impl_.entries_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::com::android::fastdeploy::APKDump)},
        {12, -1, -1, sizeof(::com::android::fastdeploy::APKEntry)},
        {23, -1, -1, sizeof(::com::android::fastdeploy::APKMetaData)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::com::android::fastdeploy::_APKDump_default_instance_._instance,
    &::com::android::fastdeploy::_APKEntry_default_instance_._instance,
    &::com::android::fastdeploy::_APKMetaData_default_instance_._instance,
};
const char descriptor_table_protodef_ApkEntry_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016ApkEntry.proto\022\026com.android.fastdeploy"
    "\"M\n\007APKDump\022\014\n\004name\030\001 \001(\t\022\n\n\002cd\030\002 \001(\014\022\021\n"
    "\tsignature\030\003 \001(\014\022\025\n\rabsolute_path\030\004 \001(\t\""
    "=\n\010APKEntry\022\013\n\003md5\030\001 \001(\014\022\022\n\ndataOffset\030\002"
    " \001(\003\022\020\n\010dataSize\030\003 \001(\003\"W\n\013APKMetaData\022\025\n"
    "\rabsolute_path\030\001 \001(\t\0221\n\007entries\030\002 \003(\0132 ."
    "com.android.fastdeploy.APKEntryB)\n\026com.a"
    "ndroid.fastdeployB\rApkEntryProtoP\001b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_ApkEntry_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ApkEntry_2eproto = {
    false,
    false,
    322,
    descriptor_table_protodef_ApkEntry_2eproto,
    "ApkEntry.proto",
    &descriptor_table_ApkEntry_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_ApkEntry_2eproto::offsets,
    file_level_metadata_ApkEntry_2eproto,
    file_level_enum_descriptors_ApkEntry_2eproto,
    file_level_service_descriptors_ApkEntry_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ApkEntry_2eproto_getter() {
  return &descriptor_table_ApkEntry_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ApkEntry_2eproto(&descriptor_table_ApkEntry_2eproto);
namespace com {
namespace android {
namespace fastdeploy {
// ===================================================================

class APKDump::_Internal {
 public:
};

APKDump::APKDump(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.android.fastdeploy.APKDump)
}
inline PROTOBUF_NDEBUG_INLINE APKDump::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        cd_(arena, from.cd_),
        signature_(arena, from.signature_),
        absolute_path_(arena, from.absolute_path_),
        _cached_size_{0} {}

APKDump::APKDump(
    ::google::protobuf::Arena* arena,
    const APKDump& from)
    : ::google::protobuf::Message(arena) {
  APKDump* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:com.android.fastdeploy.APKDump)
}
inline PROTOBUF_NDEBUG_INLINE APKDump::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        cd_(arena),
        signature_(arena),
        absolute_path_(arena),
        _cached_size_{0} {}

inline void APKDump::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
APKDump::~APKDump() {
  // @@protoc_insertion_point(destructor:com.android.fastdeploy.APKDump)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void APKDump::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.cd_.Destroy();
  _impl_.signature_.Destroy();
  _impl_.absolute_path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void APKDump::Clear() {
// @@protoc_insertion_point(message_clear_start:com.android.fastdeploy.APKDump)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.cd_.ClearToEmpty();
  _impl_.signature_.ClearToEmpty();
  _impl_.absolute_path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* APKDump::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 56, 2> APKDump::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_APKDump_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string absolute_path = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(APKDump, _impl_.absolute_path_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(APKDump, _impl_.name_)}},
    // bytes cd = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(APKDump, _impl_.cd_)}},
    // bytes signature = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(APKDump, _impl_.signature_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(APKDump, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes cd = 2;
    {PROTOBUF_FIELD_OFFSET(APKDump, _impl_.cd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes signature = 3;
    {PROTOBUF_FIELD_OFFSET(APKDump, _impl_.signature_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string absolute_path = 4;
    {PROTOBUF_FIELD_OFFSET(APKDump, _impl_.absolute_path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\4\0\0\15\0\0\0"
    "com.android.fastdeploy.APKDump"
    "name"
    "absolute_path"
  }},
};

::uint8_t* APKDump::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.android.fastdeploy.APKDump)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.android.fastdeploy.APKDump.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes cd = 2;
  if (!this->_internal_cd().empty()) {
    const std::string& _s = this->_internal_cd();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // bytes signature = 3;
  if (!this->_internal_signature().empty()) {
    const std::string& _s = this->_internal_signature();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // string absolute_path = 4;
  if (!this->_internal_absolute_path().empty()) {
    const std::string& _s = this->_internal_absolute_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.android.fastdeploy.APKDump.absolute_path");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.android.fastdeploy.APKDump)
  return target;
}

::size_t APKDump::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.android.fastdeploy.APKDump)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // bytes cd = 2;
  if (!this->_internal_cd().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_cd());
  }

  // bytes signature = 3;
  if (!this->_internal_signature().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_signature());
  }

  // string absolute_path = 4;
  if (!this->_internal_absolute_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_absolute_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData APKDump::_class_data_ = {
    APKDump::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* APKDump::GetClassData() const {
  return &_class_data_;
}

void APKDump::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<APKDump*>(&to_msg);
  auto& from = static_cast<const APKDump&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.android.fastdeploy.APKDump)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_cd().empty()) {
    _this->_internal_set_cd(from._internal_cd());
  }
  if (!from._internal_signature().empty()) {
    _this->_internal_set_signature(from._internal_signature());
  }
  if (!from._internal_absolute_path().empty()) {
    _this->_internal_set_absolute_path(from._internal_absolute_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void APKDump::CopyFrom(const APKDump& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.android.fastdeploy.APKDump)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool APKDump::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* APKDump::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void APKDump::InternalSwap(APKDump* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cd_, &other->_impl_.cd_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signature_, &other->_impl_.signature_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.absolute_path_, &other->_impl_.absolute_path_, arena);
}

::google::protobuf::Metadata APKDump::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ApkEntry_2eproto_getter, &descriptor_table_ApkEntry_2eproto_once,
      file_level_metadata_ApkEntry_2eproto[0]);
}
// ===================================================================

class APKEntry::_Internal {
 public:
};

APKEntry::APKEntry(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.android.fastdeploy.APKEntry)
}
inline PROTOBUF_NDEBUG_INLINE APKEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : md5_(arena, from.md5_),
        _cached_size_{0} {}

APKEntry::APKEntry(
    ::google::protobuf::Arena* arena,
    const APKEntry& from)
    : ::google::protobuf::Message(arena) {
  APKEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dataoffset_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, dataoffset_),
           offsetof(Impl_, datasize_) -
               offsetof(Impl_, dataoffset_) +
               sizeof(Impl_::datasize_));

  // @@protoc_insertion_point(copy_constructor:com.android.fastdeploy.APKEntry)
}
inline PROTOBUF_NDEBUG_INLINE APKEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : md5_(arena),
        _cached_size_{0} {}

inline void APKEntry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dataoffset_),
           0,
           offsetof(Impl_, datasize_) -
               offsetof(Impl_, dataoffset_) +
               sizeof(Impl_::datasize_));
}
APKEntry::~APKEntry() {
  // @@protoc_insertion_point(destructor:com.android.fastdeploy.APKEntry)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void APKEntry::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.md5_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void APKEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:com.android.fastdeploy.APKEntry)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.md5_.ClearToEmpty();
  ::memset(&_impl_.dataoffset_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.datasize_) -
      reinterpret_cast<char*>(&_impl_.dataoffset_)) + sizeof(_impl_.datasize_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* APKEntry::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> APKEntry::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_APKEntry_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes md5 = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.md5_)}},
    // int64 dataOffset = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(APKEntry, _impl_.dataoffset_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.dataoffset_)}},
    // int64 dataSize = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(APKEntry, _impl_.datasize_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.datasize_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes md5 = 1;
    {PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.md5_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 dataOffset = 2;
    {PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.dataoffset_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 dataSize = 3;
    {PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.datasize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* APKEntry::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.android.fastdeploy.APKEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes md5 = 1;
  if (!this->_internal_md5().empty()) {
    const std::string& _s = this->_internal_md5();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // int64 dataOffset = 2;
  if (this->_internal_dataoffset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_dataoffset(), target);
  }

  // int64 dataSize = 3;
  if (this->_internal_datasize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_datasize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.android.fastdeploy.APKEntry)
  return target;
}

::size_t APKEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.android.fastdeploy.APKEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes md5 = 1;
  if (!this->_internal_md5().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_md5());
  }

  // int64 dataOffset = 2;
  if (this->_internal_dataoffset() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_dataoffset());
  }

  // int64 dataSize = 3;
  if (this->_internal_datasize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_datasize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData APKEntry::_class_data_ = {
    APKEntry::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* APKEntry::GetClassData() const {
  return &_class_data_;
}

void APKEntry::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<APKEntry*>(&to_msg);
  auto& from = static_cast<const APKEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.android.fastdeploy.APKEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_md5().empty()) {
    _this->_internal_set_md5(from._internal_md5());
  }
  if (from._internal_dataoffset() != 0) {
    _this->_internal_set_dataoffset(from._internal_dataoffset());
  }
  if (from._internal_datasize() != 0) {
    _this->_internal_set_datasize(from._internal_datasize());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void APKEntry::CopyFrom(const APKEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.android.fastdeploy.APKEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool APKEntry::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* APKEntry::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void APKEntry::InternalSwap(APKEntry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.md5_, &other->_impl_.md5_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.datasize_)
      + sizeof(APKEntry::_impl_.datasize_)
      - PROTOBUF_FIELD_OFFSET(APKEntry, _impl_.dataoffset_)>(
          reinterpret_cast<char*>(&_impl_.dataoffset_),
          reinterpret_cast<char*>(&other->_impl_.dataoffset_));
}

::google::protobuf::Metadata APKEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ApkEntry_2eproto_getter, &descriptor_table_ApkEntry_2eproto_once,
      file_level_metadata_ApkEntry_2eproto[1]);
}
// ===================================================================

class APKMetaData::_Internal {
 public:
};

APKMetaData::APKMetaData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.android.fastdeploy.APKMetaData)
}
inline PROTOBUF_NDEBUG_INLINE APKMetaData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : entries_{visibility, arena, from.entries_},
        absolute_path_(arena, from.absolute_path_),
        _cached_size_{0} {}

APKMetaData::APKMetaData(
    ::google::protobuf::Arena* arena,
    const APKMetaData& from)
    : ::google::protobuf::Message(arena) {
  APKMetaData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:com.android.fastdeploy.APKMetaData)
}
inline PROTOBUF_NDEBUG_INLINE APKMetaData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : entries_{visibility, arena},
        absolute_path_(arena),
        _cached_size_{0} {}

inline void APKMetaData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
APKMetaData::~APKMetaData() {
  // @@protoc_insertion_point(destructor:com.android.fastdeploy.APKMetaData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void APKMetaData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.absolute_path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void APKMetaData::Clear() {
// @@protoc_insertion_point(message_clear_start:com.android.fastdeploy.APKMetaData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entries_.Clear();
  _impl_.absolute_path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* APKMetaData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 56, 2> APKMetaData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_APKMetaData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .com.android.fastdeploy.APKEntry entries = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(APKMetaData, _impl_.entries_)}},
    // string absolute_path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(APKMetaData, _impl_.absolute_path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string absolute_path = 1;
    {PROTOBUF_FIELD_OFFSET(APKMetaData, _impl_.absolute_path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .com.android.fastdeploy.APKEntry entries = 2;
    {PROTOBUF_FIELD_OFFSET(APKMetaData, _impl_.entries_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::com::android::fastdeploy::APKEntry>()},
  }}, {{
    "\42\15\0\0\0\0\0\0"
    "com.android.fastdeploy.APKMetaData"
    "absolute_path"
  }},
};

::uint8_t* APKMetaData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.android.fastdeploy.APKMetaData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string absolute_path = 1;
  if (!this->_internal_absolute_path().empty()) {
    const std::string& _s = this->_internal_absolute_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.android.fastdeploy.APKMetaData.absolute_path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .com.android.fastdeploy.APKEntry entries = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_entries_size()); i < n; i++) {
    const auto& repfield = this->_internal_entries().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.android.fastdeploy.APKMetaData)
  return target;
}

::size_t APKMetaData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.android.fastdeploy.APKMetaData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .com.android.fastdeploy.APKEntry entries = 2;
  total_size += 1UL * this->_internal_entries_size();
  for (const auto& msg : this->_internal_entries()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string absolute_path = 1;
  if (!this->_internal_absolute_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_absolute_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData APKMetaData::_class_data_ = {
    APKMetaData::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* APKMetaData::GetClassData() const {
  return &_class_data_;
}

void APKMetaData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<APKMetaData*>(&to_msg);
  auto& from = static_cast<const APKMetaData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.android.fastdeploy.APKMetaData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_entries()->MergeFrom(
      from._internal_entries());
  if (!from._internal_absolute_path().empty()) {
    _this->_internal_set_absolute_path(from._internal_absolute_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void APKMetaData::CopyFrom(const APKMetaData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.android.fastdeploy.APKMetaData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool APKMetaData::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* APKMetaData::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void APKMetaData::InternalSwap(APKMetaData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entries_.InternalSwap(&other->_impl_.entries_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.absolute_path_, &other->_impl_.absolute_path_, arena);
}

::google::protobuf::Metadata APKMetaData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ApkEntry_2eproto_getter, &descriptor_table_ApkEntry_2eproto_once,
      file_level_metadata_ApkEntry_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace fastdeploy
}  // namespace android
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
