// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_processes.proto

#include "app_processes.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace adb {
namespace proto {

inline constexpr ProcessEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : architecture_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pid_{::int64_t{0}},
        debuggable_{false},
        profileable_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProcessEntry::ProcessEntry(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProcessEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessEntryDefaultTypeInternal() {}
  union {
    ProcessEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessEntryDefaultTypeInternal _ProcessEntry_default_instance_;

inline constexpr AppProcesses::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : process_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AppProcesses::AppProcesses(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AppProcessesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AppProcessesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppProcessesDefaultTypeInternal() {}
  union {
    AppProcesses _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppProcessesDefaultTypeInternal _AppProcesses_default_instance_;
}  // namespace proto
}  // namespace adb
static ::_pb::Metadata file_level_metadata_app_5fprocesses_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_app_5fprocesses_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_app_5fprocesses_2eproto = nullptr;
const ::uint32_t TableStruct_app_5fprocesses_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::adb::proto::ProcessEntry, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::adb::proto::ProcessEntry, _impl_.pid_),
    PROTOBUF_FIELD_OFFSET(::adb::proto::ProcessEntry, _impl_.debuggable_),
    PROTOBUF_FIELD_OFFSET(::adb::proto::ProcessEntry, _impl_.profileable_),
    PROTOBUF_FIELD_OFFSET(::adb::proto::ProcessEntry, _impl_.architecture_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::adb::proto::AppProcesses, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::adb::proto::AppProcesses, _impl_.process_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::adb::proto::ProcessEntry)},
        {12, -1, -1, sizeof(::adb::proto::AppProcesses)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::adb::proto::_ProcessEntry_default_instance_._instance,
    &::adb::proto::_AppProcesses_default_instance_._instance,
};
const char descriptor_table_protodef_app_5fprocesses_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\023app_processes.proto\022\tadb.proto\"Z\n\014Proc"
    "essEntry\022\013\n\003pid\030\001 \001(\003\022\022\n\ndebuggable\030\002 \001("
    "\010\022\023\n\013profileable\030\003 \001(\010\022\024\n\014architecture\030\004"
    " \001(\t\"8\n\014AppProcesses\022(\n\007process\030\001 \003(\0132\027."
    "adb.proto.ProcessEntryB2\n\035com.android.se"
    "rver.adb.protosB\021AppProcessesProtob\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_app_5fprocesses_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_app_5fprocesses_2eproto = {
    false,
    false,
    242,
    descriptor_table_protodef_app_5fprocesses_2eproto,
    "app_processes.proto",
    &descriptor_table_app_5fprocesses_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_app_5fprocesses_2eproto::offsets,
    file_level_metadata_app_5fprocesses_2eproto,
    file_level_enum_descriptors_app_5fprocesses_2eproto,
    file_level_service_descriptors_app_5fprocesses_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_app_5fprocesses_2eproto_getter() {
  return &descriptor_table_app_5fprocesses_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_app_5fprocesses_2eproto(&descriptor_table_app_5fprocesses_2eproto);
namespace adb {
namespace proto {
// ===================================================================

class ProcessEntry::_Internal {
 public:
};

ProcessEntry::ProcessEntry(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:adb.proto.ProcessEntry)
}
inline PROTOBUF_NDEBUG_INLINE ProcessEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : architecture_(arena, from.architecture_),
        _cached_size_{0} {}

ProcessEntry::ProcessEntry(
    ::google::protobuf::Arena* arena,
    const ProcessEntry& from)
    : ::google::protobuf::Message(arena) {
  ProcessEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pid_),
           offsetof(Impl_, profileable_) -
               offsetof(Impl_, pid_) +
               sizeof(Impl_::profileable_));

  // @@protoc_insertion_point(copy_constructor:adb.proto.ProcessEntry)
}
inline PROTOBUF_NDEBUG_INLINE ProcessEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : architecture_(arena),
        _cached_size_{0} {}

inline void ProcessEntry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pid_),
           0,
           offsetof(Impl_, profileable_) -
               offsetof(Impl_, pid_) +
               sizeof(Impl_::profileable_));
}
ProcessEntry::~ProcessEntry() {
  // @@protoc_insertion_point(destructor:adb.proto.ProcessEntry)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProcessEntry::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.architecture_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ProcessEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:adb.proto.ProcessEntry)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.architecture_.ClearToEmpty();
  ::memset(&_impl_.pid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.profileable_) -
      reinterpret_cast<char*>(&_impl_.pid_)) + sizeof(_impl_.profileable_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProcessEntry::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 43, 2> ProcessEntry::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProcessEntry_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string architecture = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.architecture_)}},
    // int64 pid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ProcessEntry, _impl_.pid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.pid_)}},
    // bool debuggable = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ProcessEntry, _impl_.debuggable_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.debuggable_)}},
    // bool profileable = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ProcessEntry, _impl_.profileable_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.profileable_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 pid = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.pid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool debuggable = 2;
    {PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.debuggable_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool profileable = 3;
    {PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.profileable_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string architecture = 4;
    {PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.architecture_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\0\0\0\14\0\0\0"
    "adb.proto.ProcessEntry"
    "architecture"
  }},
};

::uint8_t* ProcessEntry::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:adb.proto.ProcessEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 pid = 1;
  if (this->_internal_pid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_pid(), target);
  }

  // bool debuggable = 2;
  if (this->_internal_debuggable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_debuggable(), target);
  }

  // bool profileable = 3;
  if (this->_internal_profileable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_profileable(), target);
  }

  // string architecture = 4;
  if (!this->_internal_architecture().empty()) {
    const std::string& _s = this->_internal_architecture();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "adb.proto.ProcessEntry.architecture");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:adb.proto.ProcessEntry)
  return target;
}

::size_t ProcessEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:adb.proto.ProcessEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string architecture = 4;
  if (!this->_internal_architecture().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_architecture());
  }

  // int64 pid = 1;
  if (this->_internal_pid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_pid());
  }

  // bool debuggable = 2;
  if (this->_internal_debuggable() != 0) {
    total_size += 2;
  }

  // bool profileable = 3;
  if (this->_internal_profileable() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProcessEntry::_class_data_ = {
    ProcessEntry::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ProcessEntry::GetClassData() const {
  return &_class_data_;
}

void ProcessEntry::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProcessEntry*>(&to_msg);
  auto& from = static_cast<const ProcessEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:adb.proto.ProcessEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_architecture().empty()) {
    _this->_internal_set_architecture(from._internal_architecture());
  }
  if (from._internal_pid() != 0) {
    _this->_internal_set_pid(from._internal_pid());
  }
  if (from._internal_debuggable() != 0) {
    _this->_internal_set_debuggable(from._internal_debuggable());
  }
  if (from._internal_profileable() != 0) {
    _this->_internal_set_profileable(from._internal_profileable());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessEntry::CopyFrom(const ProcessEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:adb.proto.ProcessEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProcessEntry::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ProcessEntry::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ProcessEntry::InternalSwap(ProcessEntry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.architecture_, &other->_impl_.architecture_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.profileable_)
      + sizeof(ProcessEntry::_impl_.profileable_)
      - PROTOBUF_FIELD_OFFSET(ProcessEntry, _impl_.pid_)>(
          reinterpret_cast<char*>(&_impl_.pid_),
          reinterpret_cast<char*>(&other->_impl_.pid_));
}

::google::protobuf::Metadata ProcessEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_app_5fprocesses_2eproto_getter, &descriptor_table_app_5fprocesses_2eproto_once,
      file_level_metadata_app_5fprocesses_2eproto[0]);
}
// ===================================================================

class AppProcesses::_Internal {
 public:
};

AppProcesses::AppProcesses(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:adb.proto.AppProcesses)
}
inline PROTOBUF_NDEBUG_INLINE AppProcesses::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : process_{visibility, arena, from.process_},
        _cached_size_{0} {}

AppProcesses::AppProcesses(
    ::google::protobuf::Arena* arena,
    const AppProcesses& from)
    : ::google::protobuf::Message(arena) {
  AppProcesses* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:adb.proto.AppProcesses)
}
inline PROTOBUF_NDEBUG_INLINE AppProcesses::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : process_{visibility, arena},
        _cached_size_{0} {}

inline void AppProcesses::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AppProcesses::~AppProcesses() {
  // @@protoc_insertion_point(destructor:adb.proto.AppProcesses)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AppProcesses::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AppProcesses::Clear() {
// @@protoc_insertion_point(message_clear_start:adb.proto.AppProcesses)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.process_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AppProcesses::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> AppProcesses::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AppProcesses_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .adb.proto.ProcessEntry process = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AppProcesses, _impl_.process_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .adb.proto.ProcessEntry process = 1;
    {PROTOBUF_FIELD_OFFSET(AppProcesses, _impl_.process_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::adb::proto::ProcessEntry>()},
  }}, {{
  }},
};

::uint8_t* AppProcesses::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:adb.proto.AppProcesses)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .adb.proto.ProcessEntry process = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_process_size()); i < n; i++) {
    const auto& repfield = this->_internal_process().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:adb.proto.AppProcesses)
  return target;
}

::size_t AppProcesses::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:adb.proto.AppProcesses)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .adb.proto.ProcessEntry process = 1;
  total_size += 1UL * this->_internal_process_size();
  for (const auto& msg : this->_internal_process()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AppProcesses::_class_data_ = {
    AppProcesses::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AppProcesses::GetClassData() const {
  return &_class_data_;
}

void AppProcesses::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AppProcesses*>(&to_msg);
  auto& from = static_cast<const AppProcesses&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:adb.proto.AppProcesses)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_process()->MergeFrom(
      from._internal_process());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AppProcesses::CopyFrom(const AppProcesses& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:adb.proto.AppProcesses)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AppProcesses::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AppProcesses::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AppProcesses::InternalSwap(AppProcesses* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.process_.InternalSwap(&other->_impl_.process_);
}

::google::protobuf::Metadata AppProcesses::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_app_5fprocesses_2eproto_getter, &descriptor_table_app_5fprocesses_2eproto_once,
      file_level_metadata_app_5fprocesses_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace adb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
