// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_processes.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_app_5fprocesses_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_app_5fprocesses_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_app_5fprocesses_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_app_5fprocesses_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_app_5fprocesses_2eproto;
namespace adb {
namespace proto {
class AppProcesses;
struct AppProcessesDefaultTypeInternal;
extern AppProcessesDefaultTypeInternal _AppProcesses_default_instance_;
class ProcessEntry;
struct ProcessEntryDefaultTypeInternal;
extern ProcessEntryDefaultTypeInternal _ProcessEntry_default_instance_;
}  // namespace proto
}  // namespace adb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace adb {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class ProcessEntry final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:adb.proto.ProcessEntry) */ {
 public:
  inline ProcessEntry() : ProcessEntry(nullptr) {}
  ~ProcessEntry() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ProcessEntry(::google::protobuf::internal::ConstantInitialized);

  inline ProcessEntry(const ProcessEntry& from)
      : ProcessEntry(nullptr, from) {}
  ProcessEntry(ProcessEntry&& from) noexcept
    : ProcessEntry() {
    *this = ::std::move(from);
  }

  inline ProcessEntry& operator=(const ProcessEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessEntry& operator=(ProcessEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessEntry* internal_default_instance() {
    return reinterpret_cast<const ProcessEntry*>(
               &_ProcessEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProcessEntry& a, ProcessEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessEntry* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProcessEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ProcessEntry& from) {
    ProcessEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProcessEntry* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "adb.proto.ProcessEntry";
  }
  protected:
  explicit ProcessEntry(::google::protobuf::Arena* arena);
  ProcessEntry(::google::protobuf::Arena* arena, const ProcessEntry& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArchitectureFieldNumber = 4,
    kPidFieldNumber = 1,
    kDebuggableFieldNumber = 2,
    kProfileableFieldNumber = 3,
  };
  // string architecture = 4;
  void clear_architecture() ;
  const std::string& architecture() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_architecture(Arg_&& arg, Args_... args);
  std::string* mutable_architecture();
  PROTOBUF_NODISCARD std::string* release_architecture();
  void set_allocated_architecture(std::string* value);

  private:
  const std::string& _internal_architecture() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_architecture(
      const std::string& value);
  std::string* _internal_mutable_architecture();

  public:
  // int64 pid = 1;
  void clear_pid() ;
  ::int64_t pid() const;
  void set_pid(::int64_t value);

  private:
  ::int64_t _internal_pid() const;
  void _internal_set_pid(::int64_t value);

  public:
  // bool debuggable = 2;
  void clear_debuggable() ;
  bool debuggable() const;
  void set_debuggable(bool value);

  private:
  bool _internal_debuggable() const;
  void _internal_set_debuggable(bool value);

  public:
  // bool profileable = 3;
  void clear_profileable() ;
  bool profileable() const;
  void set_profileable(bool value);

  private:
  bool _internal_profileable() const;
  void _internal_set_profileable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:adb.proto.ProcessEntry)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      43, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr architecture_;
    ::int64_t pid_;
    bool debuggable_;
    bool profileable_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_5fprocesses_2eproto;
};// -------------------------------------------------------------------

class AppProcesses final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:adb.proto.AppProcesses) */ {
 public:
  inline AppProcesses() : AppProcesses(nullptr) {}
  ~AppProcesses() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AppProcesses(::google::protobuf::internal::ConstantInitialized);

  inline AppProcesses(const AppProcesses& from)
      : AppProcesses(nullptr, from) {}
  AppProcesses(AppProcesses&& from) noexcept
    : AppProcesses() {
    *this = ::std::move(from);
  }

  inline AppProcesses& operator=(const AppProcesses& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppProcesses& operator=(AppProcesses&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppProcesses& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppProcesses* internal_default_instance() {
    return reinterpret_cast<const AppProcesses*>(
               &_AppProcesses_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppProcesses& a, AppProcesses& b) {
    a.Swap(&b);
  }
  inline void Swap(AppProcesses* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppProcesses* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppProcesses* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppProcesses>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AppProcesses& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AppProcesses& from) {
    AppProcesses::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AppProcesses* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "adb.proto.AppProcesses";
  }
  protected:
  explicit AppProcesses(::google::protobuf::Arena* arena);
  AppProcesses(::google::protobuf::Arena* arena, const AppProcesses& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProcessFieldNumber = 1,
  };
  // repeated .adb.proto.ProcessEntry process = 1;
  int process_size() const;
  private:
  int _internal_process_size() const;

  public:
  void clear_process() ;
  ::adb::proto::ProcessEntry* mutable_process(int index);
  ::google::protobuf::RepeatedPtrField< ::adb::proto::ProcessEntry >*
      mutable_process();
  private:
  const ::google::protobuf::RepeatedPtrField<::adb::proto::ProcessEntry>& _internal_process() const;
  ::google::protobuf::RepeatedPtrField<::adb::proto::ProcessEntry>* _internal_mutable_process();
  public:
  const ::adb::proto::ProcessEntry& process(int index) const;
  ::adb::proto::ProcessEntry* add_process();
  const ::google::protobuf::RepeatedPtrField< ::adb::proto::ProcessEntry >&
      process() const;
  // @@protoc_insertion_point(class_scope:adb.proto.AppProcesses)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::adb::proto::ProcessEntry > process_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_5fprocesses_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProcessEntry

// int64 pid = 1;
inline void ProcessEntry::clear_pid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.pid_ = ::int64_t{0};
}
inline ::int64_t ProcessEntry::pid() const {
  // @@protoc_insertion_point(field_get:adb.proto.ProcessEntry.pid)
  return _internal_pid();
}
inline void ProcessEntry::set_pid(::int64_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:adb.proto.ProcessEntry.pid)
}
inline ::int64_t ProcessEntry::_internal_pid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.pid_;
}
inline void ProcessEntry::_internal_set_pid(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pid_ = value;
}

// bool debuggable = 2;
inline void ProcessEntry::clear_debuggable() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.debuggable_ = false;
}
inline bool ProcessEntry::debuggable() const {
  // @@protoc_insertion_point(field_get:adb.proto.ProcessEntry.debuggable)
  return _internal_debuggable();
}
inline void ProcessEntry::set_debuggable(bool value) {
  _internal_set_debuggable(value);
  // @@protoc_insertion_point(field_set:adb.proto.ProcessEntry.debuggable)
}
inline bool ProcessEntry::_internal_debuggable() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.debuggable_;
}
inline void ProcessEntry::_internal_set_debuggable(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.debuggable_ = value;
}

// bool profileable = 3;
inline void ProcessEntry::clear_profileable() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.profileable_ = false;
}
inline bool ProcessEntry::profileable() const {
  // @@protoc_insertion_point(field_get:adb.proto.ProcessEntry.profileable)
  return _internal_profileable();
}
inline void ProcessEntry::set_profileable(bool value) {
  _internal_set_profileable(value);
  // @@protoc_insertion_point(field_set:adb.proto.ProcessEntry.profileable)
}
inline bool ProcessEntry::_internal_profileable() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.profileable_;
}
inline void ProcessEntry::_internal_set_profileable(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.profileable_ = value;
}

// string architecture = 4;
inline void ProcessEntry::clear_architecture() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.architecture_.ClearToEmpty();
}
inline const std::string& ProcessEntry::architecture() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:adb.proto.ProcessEntry.architecture)
  return _internal_architecture();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ProcessEntry::set_architecture(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.architecture_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:adb.proto.ProcessEntry.architecture)
}
inline std::string* ProcessEntry::mutable_architecture() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_architecture();
  // @@protoc_insertion_point(field_mutable:adb.proto.ProcessEntry.architecture)
  return _s;
}
inline const std::string& ProcessEntry::_internal_architecture() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.architecture_.Get();
}
inline void ProcessEntry::_internal_set_architecture(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.architecture_.Set(value, GetArena());
}
inline std::string* ProcessEntry::_internal_mutable_architecture() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.architecture_.Mutable( GetArena());
}
inline std::string* ProcessEntry::release_architecture() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:adb.proto.ProcessEntry.architecture)
  return _impl_.architecture_.Release();
}
inline void ProcessEntry::set_allocated_architecture(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.architecture_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.architecture_.IsDefault()) {
          _impl_.architecture_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:adb.proto.ProcessEntry.architecture)
}

// -------------------------------------------------------------------

// AppProcesses

// repeated .adb.proto.ProcessEntry process = 1;
inline int AppProcesses::_internal_process_size() const {
  return _internal_process().size();
}
inline int AppProcesses::process_size() const {
  return _internal_process_size();
}
inline void AppProcesses::clear_process() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.process_.Clear();
}
inline ::adb::proto::ProcessEntry* AppProcesses::mutable_process(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:adb.proto.AppProcesses.process)
  return _internal_mutable_process()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::adb::proto::ProcessEntry>* AppProcesses::mutable_process()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:adb.proto.AppProcesses.process)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_process();
}
inline const ::adb::proto::ProcessEntry& AppProcesses::process(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:adb.proto.AppProcesses.process)
  return _internal_process().Get(index);
}
inline ::adb::proto::ProcessEntry* AppProcesses::add_process() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::adb::proto::ProcessEntry* _add = _internal_mutable_process()->Add();
  // @@protoc_insertion_point(field_add:adb.proto.AppProcesses.process)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::adb::proto::ProcessEntry>& AppProcesses::process() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:adb.proto.AppProcesses.process)
  return _internal_process();
}
inline const ::google::protobuf::RepeatedPtrField<::adb::proto::ProcessEntry>&
AppProcesses::_internal_process() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.process_;
}
inline ::google::protobuf::RepeatedPtrField<::adb::proto::ProcessEntry>*
AppProcesses::_internal_mutable_process() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.process_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace adb


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_app_5fprocesses_2eproto_2epb_2eh
