// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pairing.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pairing_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pairing_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pairing_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pairing_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pairing_2eproto;
namespace adb {
namespace proto {
class PairingPacket;
struct PairingPacketDefaultTypeInternal;
extern PairingPacketDefaultTypeInternal _PairingPacket_default_instance_;
}  // namespace proto
}  // namespace adb
PROTOBUF_NAMESPACE_OPEN
template<> ::adb::proto::PairingPacket* Arena::CreateMaybeMessage<::adb::proto::PairingPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace adb {
namespace proto {

enum PairingPacket_Type : int {
  PairingPacket_Type_SPAKE2_MSG = 0,
  PairingPacket_Type_PEER_INFO = 1,
  PairingPacket_Type_PairingPacket_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PairingPacket_Type_PairingPacket_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PairingPacket_Type_IsValid(int value);
constexpr PairingPacket_Type PairingPacket_Type_Type_MIN = PairingPacket_Type_SPAKE2_MSG;
constexpr PairingPacket_Type PairingPacket_Type_Type_MAX = PairingPacket_Type_PEER_INFO;
constexpr int PairingPacket_Type_Type_ARRAYSIZE = PairingPacket_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PairingPacket_Type_descriptor();
template<typename T>
inline const std::string& PairingPacket_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PairingPacket_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PairingPacket_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PairingPacket_Type_descriptor(), enum_t_value);
}
inline bool PairingPacket_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PairingPacket_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PairingPacket_Type>(
    PairingPacket_Type_descriptor(), name, value);
}
// ===================================================================

class PairingPacket final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:adb.proto.PairingPacket) */ {
 public:
  inline PairingPacket() : PairingPacket(nullptr) {}
  explicit PROTOBUF_CONSTEXPR PairingPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PairingPacket(const PairingPacket& from);
  PairingPacket(PairingPacket&& from) noexcept
    : PairingPacket() {
    *this = ::std::move(from);
  }

  inline PairingPacket& operator=(const PairingPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline PairingPacket& operator=(PairingPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PairingPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const PairingPacket* internal_default_instance() {
    return reinterpret_cast<const PairingPacket*>(
               &_PairingPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PairingPacket& a, PairingPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(PairingPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PairingPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PairingPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PairingPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PairingPacket& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PairingPacket& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "adb.proto.PairingPacket";
  }
  protected:
  explicit PairingPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PairingPacket_Type Type;
  static constexpr Type SPAKE2_MSG =
    PairingPacket_Type_SPAKE2_MSG;
  static constexpr Type PEER_INFO =
    PairingPacket_Type_PEER_INFO;
  static inline bool Type_IsValid(int value) {
    return PairingPacket_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    PairingPacket_Type_Type_MIN;
  static constexpr Type Type_MAX =
    PairingPacket_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    PairingPacket_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return PairingPacket_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return PairingPacket_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return PairingPacket_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:adb.proto.PairingPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_pairing_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PairingPacket

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace adb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::adb::proto::PairingPacket_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::adb::proto::PairingPacket_Type>() {
  return ::adb::proto::PairingPacket_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pairing_2eproto
