// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pairing.proto

#include "pairing.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace adb {
namespace proto {
      template <typename>
PROTOBUF_CONSTEXPR PairingPacket::PairingPacket(::_pbi::ConstantInitialized) {}
struct PairingPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PairingPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PairingPacketDefaultTypeInternal() {}
  union {
    PairingPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PairingPacketDefaultTypeInternal _PairingPacket_default_instance_;
}  // namespace proto
}  // namespace adb
static ::_pb::Metadata file_level_metadata_pairing_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_pairing_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_pairing_2eproto = nullptr;
const ::uint32_t TableStruct_pairing_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::adb::proto::PairingPacket, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::adb::proto::PairingPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::adb::proto::_PairingPacket_default_instance_._instance,
};
const char descriptor_table_protodef_pairing_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rpairing.proto\022\tadb.proto\"6\n\rPairingPac"
    "ket\"%\n\004Type\022\016\n\nSPAKE2_MSG\020\000\022\r\n\tPEER_INFO"
    "\020\001B-\n\035com.android.server.adb.protosB\014Pai"
    "ringProtob\006proto3"
};
static ::absl::once_flag descriptor_table_pairing_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pairing_2eproto = {
    false,
    false,
    137,
    descriptor_table_protodef_pairing_2eproto,
    "pairing.proto",
    &descriptor_table_pairing_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_pairing_2eproto::offsets,
    file_level_metadata_pairing_2eproto,
    file_level_enum_descriptors_pairing_2eproto,
    file_level_service_descriptors_pairing_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pairing_2eproto_getter() {
  return &descriptor_table_pairing_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pairing_2eproto(&descriptor_table_pairing_2eproto);
namespace adb {
namespace proto {
const ::google::protobuf::EnumDescriptor* PairingPacket_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_pairing_2eproto);
  return file_level_enum_descriptors_pairing_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PairingPacket_Type_internal_data_[] = {
    131072u, 0u, };
bool PairingPacket_Type_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr PairingPacket_Type PairingPacket::SPAKE2_MSG;
constexpr PairingPacket_Type PairingPacket::PEER_INFO;
constexpr PairingPacket_Type PairingPacket::Type_MIN;
constexpr PairingPacket_Type PairingPacket::Type_MAX;
constexpr int PairingPacket::Type_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class PairingPacket::_Internal {
 public:
};

PairingPacket::PairingPacket(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:adb.proto.PairingPacket)
}
PairingPacket::PairingPacket(
    ::google::protobuf::Arena* arena,
    const PairingPacket& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PairingPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:adb.proto.PairingPacket)
}









::google::protobuf::Metadata PairingPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pairing_2eproto_getter, &descriptor_table_pairing_2eproto_once,
      file_level_metadata_pairing_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace adb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
